name: publish-docs

on:
  push:
    branches: [ develop ]

jobs:
  pubdocs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout nmrespy
        uses: actions/checkout@v2
        with:
          ref: develop
          path: develop

      - name: setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install LaTeX
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng

      - name: install and build docs
        run: |
          python -m pip install --upgrade pip
          cd develop/
          python -m pip install -r requirements.txt
          cd docs/
          python -m pip install -r requirements.txt
          sphinx-build -b html . html

      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: update gh-pages
        run: |
          cd gh-pages
          cp -r ../develop/docs/html/* .
          touch .nojekyll
          git config --local user.name "GitHub Actions"
          git config --local user.email "<>"
          git add -A
          git commit -m "Update documentation" || true
          git push
