name: publish-docs

on:
  push:
    branches: [ develop ]

jobs:
  pubdocs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout nmrespy
        uses: actions/checkout@v2
        with:
          ref: develop
          path: develop

      - name: setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install LaTeX and fonts
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-xetex dvipng

      - name: get freefonts
        run: |
          wget https://ftp.gnu.org/gnu/freefont/freefont-otf-20120503.tar.gz
          tar -xzvf freefont-otf-20120503.tar.gz
          sudo mv freefont-otf-20120503 /usr/share/fonts/opentype/freefont

      - name: install nmrespy dependencies and sphinx and build docs
        run: |
          python -m pip install --upgrade pip
          cd develop/
          python -m pip install -r requirements.txt
          cd docs/
          python -m pip install -r requirements.txt
          sphinx-build -b html . html
          sphinx-build -b latex . latex

      - name: complie with XeLaTeX
        run: |
          cd develop/docs/latex/
          xelatex nmr-espy.tex
          xelatex nmr-espy.tex

      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: update gh-pages
        run: |
          cd gh-pages
          cp -r ../develop/docs/html/* ../develop/docs/latex/nmr-espy.pdf .
          touch .nojekyll
          git config --local user.name "GitHub Actions"
          git config --local user.email "<>"
          git add -A
          git commit -m "Update documentation" || true
          git push
